[2025-02-12T18:28:46.037+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T18:28:46.067+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.transform_data manual__2025-02-12T18:28:07.884104+00:00 [queued]>
[2025-02-12T18:28:46.085+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Covid19_ETL_v2.1.transform_data manual__2025-02-12T18:28:07.884104+00:00 [queued]>
[2025-02-12T18:28:46.086+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-12T18:28:46.108+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data> on 2025-02-12 18:28:07.884104+00:00
[2025-02-12T18:28:46.130+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1944) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T18:28:46.132+0000] {standard_task_runner.py:72} INFO - Started process 1946 to run task
[2025-02-12T18:28:46.133+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Covid19_ETL_v2.1', 'transform_data', 'manual__2025-02-12T18:28:07.884104+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/covid_test.py', '--cfg-path', '/tmp/tmpk9kw8f8b']
[2025-02-12T18:28:46.137+0000] {standard_task_runner.py:105} INFO - Job 163: Subtask transform_data
[2025-02-12T18:28:46.223+0000] {task_command.py:467} INFO - Running <TaskInstance: Covid19_ETL_v2.1.transform_data manual__2025-02-12T18:28:07.884104+00:00 [running]> on host f99369d27a52
[2025-02-12T18:28:47.280+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Covid19_ETL_v2.1' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T18:28:07.884104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T18:28:07.884104+00:00'
[2025-02-12T18:28:47.283+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-12T18:28:47.344+0000] {warnings.py:112} WARNING - /opt/***/dags/covid_test.py:127: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(raw_data)

[2025-02-12T18:28:47.450+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T18:28:47.465+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-12T18:28:47.466+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Covid19_ETL_v2.1, task_id=transform_data, run_id=manual__2025-02-12T18:28:07.884104+00:00, execution_date=20250212T182807, start_date=20250212T182846, end_date=20250212T182847
[2025-02-12T18:28:47.522+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T18:28:47.544+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T18:28:47.549+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
